// lib/docxWriter.js
import { Document, Packer, Paragraph } from 'docx';

/**
 * Crée un DOCX minimal propre avec le texte fourni.
 * Chaque ligne => un paragraphe (séparateur: \n).
 */
export async function createDocxFromText(text, { title } = {}) {
  const paras = String(text || '').split('\n').map(line => new Paragraph({ text: line }));
  const doc = new Document({
    creator: 'DocSafe',
    title: title || 'DocSafe Cleaned',
    description: 'Generated by DocSafe'
  });
  doc.addSection({ children: paras });
  const buffer = await Packer.toBuffer(doc);
  return buffer;
}
