import { Document, Packer, Paragraph } from 'docx';

/** Construit un DOCX minimal propre à partir d'un texte (1 paragraphe par ligne). */
export async function createDocxFromText(text, { title } = {}) {
  const lines = String(text || '').replace(/\r\n/g, '\n').split('\n');
  const paras = lines.map(line => new Paragraph({ text: line }));
  const doc = new Document({
    creator: 'DocSafe',
    title: title || 'DocSafe Document',
    description: 'Generated by DocSafe'
  });
  doc.addSection({ children: paras });
  return await Packer.toBuffer(doc);
}
